export const OFFERS_FIXTURE = [
  {
    publicId: 'FU5D2I',
    title: 'Ingénieur en Intelligence Artificielle',
    place: {
      fullAddress: '151 Jevon Ways\nCasimirchester, AZ 12264',
      city: 'Marseille',
      zipCode: '33000',
      latitude: 31.315213,
      longitude: -147.975034,
    },
    job: {
      description:
        'Doloribus impedit hic cum. Distinctio suscipit neque eaque. Sed nisi dolores aut doloribus libero. Aut deserunt unde iure quis. Qui ut sapiente quo quo. Quaerat saepe amet voluptates dolores illo aut. Dicta distinctio cumque qui neque laudantium. Tempora error vel quibusdam in quis. Natus consequatur recusandae ut. Iste sint qui accusantium odio amet rerum a dolores. Esse placeat in culpa. Velit recusandae temporibus autem sit. Dolor saepe aut dolores architecto qui. Ex earum consequatur impedit quisquam officiis. Corporis quia consequuntur nihil quo aperiam accusamus iste. Itaque eos inventore cumque sit. Unde repudiandae magni mollitia nihil quisquam distinctio quidem magni. Architecto consequatur autem doloribus sunt dolorum. Assumenda vero possimus occaecati saepe eius possimus qui. Qui aliquam quo consequatur dolorem. Impedit sint consequuntur odit impedit maiores aut. Quo odio eligendi eaque amet doloremque. Quia molestias voluptas delectus voluptatem sed culpa. Animi labore non iure quam. Dolorum et maiores consectetur architecto culpa commodi maxime. Natus ea aliquid a iusto vel harum ipsa. Aliquam voluptas officiis omnis odit delectus adipisci. Et excepturi debitis vel et et laudantium pariatur similique. Ut dolore non molestiae libero nihil dolorem. Omnis eveniet ipsa quam rerum nihil. Qui quis quaerat eveniet iste illo. A placeat qui sint sequi delectus et aut. Ad inventore aut dignissimos eos fugit. Cumque eum odio nam fuga sint fugiat velit.',
      contractType: 'CDI',
      duration: 6,
      remote: true,
      studyLevel: 'Bac',
      startDate: '2024-11-03',
    },
    company: {
      name: 'Facebook',
      websiteUrl: 'https://www.lesch.com/excepturi-omnis-sint-tempore-voluptatem-voluptatum',
      logo: 'edf.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://www.schneider.info/ratione-rem-sit-aperiam-voluptatem',
    tag: ['Marketing Digital', 'Cloud Computing', 'Transformation Digitale', 'Support IT'],
    status: 'published',
    createdAt: '2024-10-19T12:47:17+02:00',
    endDate: '2024-11-19T00:00:00+01:00',
    slug: 'ingenieur-en-intelligence-artificielle',
    category: [
      {
        name: 'Ingénierie Logicielle',
      },
    ],
    premium: true,
    dayLast: 26,
  },
  {
    publicId: '5JVKPG',
    title: 'Responsable Marketing Digital',
    place: {
      fullAddress: '1541 Zella Overpass Suite 846\nWest Leopold, NM 98463-7320',
      city: 'Paris',
      zipCode: '59000',
      latitude: -24.818391,
      longitude: -155.193574,
    },
    job: {
      description:
        'Quia cum explicabo labore sed. Asperiores harum consequatur sed nulla nemo. Incidunt ea nam enim dolorem ullam nulla ea. Temporibus laudantium exercitationem non vitae saepe. Ut voluptas asperiores nesciunt pariatur ea. Est et asperiores quaerat alias rem odio consequuntur. Voluptas ipsum dignissimos impedit inventore. Sit similique earum voluptatem ipsam vero occaecati et. Iusto iste accusantium saepe rem provident aliquam ad omnis. Porro dolores qui explicabo. Dolores voluptates perspiciatis qui dolores itaque fugiat. Nemo et illum earum. Quod dolorum saepe rerum non et recusandae soluta. Ullam odit iusto id rerum. Voluptatem molestias commodi corrupti eius animi. Culpa repudiandae laudantium deserunt iste. Aut magnam rem voluptatem optio est sed. Illum quae dignissimos quo in dolore aspernatur. In aliquam architecto ullam qui ut optio sit ea. Ab et est illo quis quas. Exercitationem cupiditate cupiditate sit ipsum eos quo magni. Iusto magnam nostrum et corporis. Quam mollitia deleniti omnis dolor harum cupiditate alias. Quia molestias modi nemo. Itaque ipsum nostrum nemo dolores est repudiandae ab illum. Est voluptates ducimus quos adipisci. A voluptatem voluptatem expedita non facilis et. Vel culpa optio distinctio pariatur. A ratione architecto aspernatur aperiam ut in consequatur. Unde error aut veniam cupiditate esse enim. Eaque ut aut quaerat soluta sit. Aliquam eum ut ex.',
      contractType: 'CDI',
      duration: 10,
      remote: true,
      studyLevel: 'Sans diplôme',
      startDate: '2024-11-06',
    },
    company: {
      name: 'Waterman',
      websiteUrl: 'https://www.towne.net/eveniet-aut-alias-quaerat-autem-tempora-perspiciatis',
      logo: 'edf.png',
      verified: false,
      offerNumber: 1,
    },
    url: 'http://www.leuschke.com/quos-modi-itaque-cupiditate-ad-commodi',
    tag: [
      'Science des Données',
      'Droit des Entreprises',
      'Agilité',
      'Logistique',
      'Apprentissage Automatique',
    ],
    status: 'published',
    createdAt: '2024-10-18T09:03:16+02:00',
    endDate: '2024-11-18T00:00:00+01:00',
    slug: 'responsable-marketing-digital',
    category: [
      {
        name: 'Réalité Virtuelle',
      },
    ],
    premium: true,
    dayLast: 25,
  },
  {
    publicId: 'YCFAO5',
    title: 'Comptable Senior',
    place: {
      fullAddress: '35771 Casper Park\nWest Lelah, NE 36623',
      city: 'Nantes',
      zipCode: '49000',
      latitude: 36.518242,
      longitude: -170.697454,
    },
    job: {
      description:
        'Dolores exercitationem eveniet qui asperiores. Rem aut atque corporis sit officiis magnam. Reiciendis aut illo doloribus. Atque consequuntur ratione est maiores. Est rerum quo eaque esse cumque. Maxime minima ratione et nihil deserunt vitae illo. Aut inventore quisquam fugit. Nemo eveniet voluptas exercitationem voluptas provident dolore. Consequuntur minima animi distinctio explicabo esse sint minus. Ipsam occaecati asperiores amet distinctio consequuntur molestiae quis libero. Labore sunt hic sit eum voluptatem. Et provident quod consequatur nesciunt. Dolorem dolore alias aut omnis hic temporibus labore. Cupiditate quidem cupiditate quia. Cumque voluptas error perspiciatis vel sapiente laudantium ut. Mollitia maiores dolore iste sed sint. Voluptatem et asperiores voluptatem consequatur incidunt nam. Vitae officiis est aliquam. Nostrum doloremque quasi voluptatem. Qui nesciunt rem mollitia quasi debitis. Quis molestiae repellat iure et. Beatae in voluptates laboriosam officia consequatur consequatur. Est perspiciatis aut reiciendis sint et et earum. Illo consectetur harum porro dolorem. Nihil consequatur sit unde et. Quia fugit maiores ipsum illum reprehenderit. Laborum atque ducimus et. Nobis eum aut earum debitis qui dignissimos et. Excepturi omnis voluptas non et facere. In amet excepturi molestiae quasi. Ratione enim ut quo est laborum quidem sed est. Quos dignissimos sapiente molestiae illo natus. Omnis reiciendis aut inventore voluptatum. Ab qui ut dolor deserunt.',
      contractType: 'CDD',
      duration: 9,
      remote: true,
      studyLevel: 'Sans diplôme',
      startDate: '2024-11-12',
    },
    company: {
      name: 'SDV International Logistics',
      websiteUrl: 'http://bashirian.com/aliquam-nulla-officia-similique-quos-dicta.html',
      logo: 'capgemini.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://crooks.com/consequuntur-saepe-ea-aspernatur-fuga-laboriosam-voluptas',
    tag: ['Support IT', 'Cybersécurité', 'Droit des Entreprises'],
    status: 'published',
    createdAt: '2024-10-18T05:10:26+02:00',
    endDate: '2024-11-18T00:00:00+01:00',
    slug: 'comptable-senior',
    category: [
      {
        name: 'Ingénierie Logicielle',
      },
    ],
    premium: false,
    dayLast: 25,
  },
  {
    publicId: '671AO9',
    title: 'Technicien Réseau et Système',
    place: {
      fullAddress: '68946 Annabel Island Apt. 289\nPort Dashawn, OR 74248',
      city: 'Rennes',
      zipCode: '67000',
      latitude: 41.537542,
      longitude: -103.366626,
    },
    job: {
      description:
        'Esse qui voluptatem saepe. Odit molestiae tempore asperiores molestiae aut. Voluptatum aut eius hic assumenda sit rerum omnis. Laboriosam qui perferendis ratione alias rem. Esse architecto dignissimos sed et est alias maiores aut. Recusandae dolore quod dolore eligendi libero eum praesentium. Labore vitae dolores velit doloremque culpa optio libero porro. Inventore dolorem exercitationem illum expedita. Sunt voluptatibus sapiente praesentium rerum non aspernatur. Dolor fugiat repudiandae minima recusandae nulla accusamus. Eum sit est ipsum libero velit nobis. Et est nobis corporis ex. A necessitatibus inventore et vero. Ab cupiditate aut aut quisquam magni sint in. Cupiditate et reprehenderit labore nisi. Eos repellendus possimus quo labore. Doloribus ut iste voluptatem. Fugit sit consectetur aut aperiam nemo sit perspiciatis maiores. Et accusamus quis at nihil et. Autem dolores porro consequatur suscipit culpa laborum tempore aliquam. Ut tempora modi et aut nobis beatae. Ut qui earum corporis ut voluptatibus. Aut facere magnam amet. Molestiae aut natus et recusandae iste vel molestias et. Veritatis debitis similique quia eligendi soluta consequatur. Voluptatem eveniet fugit ab architecto facilis ducimus repellendus tempore. Eum et quidem beatae vero. Eum ducimus ut sed soluta facilis aut. Maxime neque sit cum quo rerum voluptatibus quo.',
      contractType: 'CDD',
      duration: 5,
      remote: true,
      studyLevel: 'CAP',
      startDate: '2024-11-04',
    },
    company: {
      name: 'Gaumont',
      websiteUrl:
        'https://bahringer.info/consectetur-eos-qui-totam-cupiditate-maxime-impedit-aut.html',
      logo: 'edf.png',
      verified: false,
      offerNumber: 1,
    },
    url: 'http://www.reichert.com/harum-cum-sit-aut-sint',
    tag: ['Logistique', 'Développement Web', 'Transformation Digitale'],
    status: 'published',
    createdAt: '2024-10-17T13:21:18+02:00',
    endDate: '2024-11-17T00:00:00+01:00',
    slug: 'technicien-reseau-et-systeme',
    category: [
      {
        name: 'Internet des Objets (IoT)',
      },
    ],
    premium: true,
    dayLast: 24,
  },
  {
    publicId: 'DUKJP8',
    title: 'Data Scientist',
    place: {
      fullAddress: '3401 Marielle Landing\nMertzchester, NH 54241-8824',
      city: 'Bordeaux',
      zipCode: '21000',
      latitude: -74.199211,
      longitude: 168.607755,
    },
    job: {
      description:
        'Consequuntur autem ipsum rerum quis ipsum autem laudantium. Similique ut quibusdam laudantium a nihil qui vitae quaerat. Recusandae labore et minima ducimus velit. Omnis illum provident et nihil qui. Porro culpa adipisci dolore aperiam. Reiciendis commodi optio neque consequatur. Sunt ut natus adipisci id et. Repudiandae in et voluptates. Atque dolor nisi et laudantium dignissimos. Animi tempora quia officia est. Ut est velit accusamus ratione magni voluptate. Aut perspiciatis modi non. Hic dolorem distinctio quo voluptatibus vel. Ea vitae autem enim dolore eum voluptate ipsam. Sunt architecto cupiditate reiciendis repudiandae vitae. Adipisci est sint voluptas consequuntur. Reprehenderit consequatur quaerat accusantium qui quo. Quis vitae enim debitis reprehenderit consequatur est harum in. Maiores recusandae aliquid aut vero. Qui explicabo est deserunt. Autem repellendus quos voluptas. Quasi quidem quia odio fugit. Enim magni tempore aut ut. Soluta est ut pariatur expedita consequatur. Eligendi quia eos doloribus sint consequuntur nam non. Quisquam nobis laudantium quae qui. Omnis animi dolor voluptatem. Voluptatum quibusdam quod necessitatibus aperiam provident. Accusantium earum magni nesciunt illo impedit qui sunt et. Dolore debitis sit necessitatibus. Accusamus sint itaque voluptatem ut. Est blanditiis qui id cumque alias nihil. Fuga eum quia accusamus qui ex non minima. Veniam sunt atque est quasi voluptatem in. Eum sunt sequi inventore et tenetur.',
      contractType: 'CDD',
      duration: 10,
      remote: true,
      studyLevel: 'CAP',
      startDate: '2024-11-18',
    },
    company: {
      name: 'Google',
      websiteUrl: 'https://davis.org/explicabo-qui-laboriosam-qui-quaerat-nobis-ad.html',
      logo: 'capgemini.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://grimes.com/',
    tag: ['Marketing Digital', 'Cybersécurité', 'Science des Données'],
    status: 'published',
    createdAt: '2024-10-16T09:05:52+02:00',
    endDate: '2024-11-16T00:00:00+01:00',
    slug: 'data-scientist',
    category: [
      {
        name: 'Internet des Objets (IoT)',
      },
    ],
    premium: false,
    dayLast: 23,
  },
  {
    publicId: 'IIR77G',
    title: 'Comptable Senior',
    place: {
      fullAddress: '58306 Dorothea Mountain Apt. 286\nArielleview, NM 70030',
      city: 'Nîmes',
      zipCode: '34000',
      latitude: -49.99526,
      longitude: -49.235984,
    },
    job: {
      description:
        'Qui veniam qui aut qui ut quisquam. Et architecto distinctio ea quia cum. Error aperiam corrupti occaecati quae doloribus. Voluptatem magni voluptatum et soluta. Iste ut accusantium odio at est eveniet. Et nihil qui tempora occaecati deleniti. Vel dolor et voluptates alias. Sapiente cupiditate atque non veniam hic veniam eveniet. Alias voluptatem incidunt earum et illum quaerat ut. Omnis dignissimos numquam in voluptatibus sit sint error. Nihil sint veritatis aut id sit tempore. Sint ea sequi hic sint repellendus. Excepturi vero voluptas tenetur omnis dolor culpa vero. Dolorum id error illum. Et quo magni quaerat nihil soluta. Et hic voluptate aut nulla laudantium cupiditate molestiae exercitationem. Sint molestias nobis recusandae quis excepturi voluptatem. Est quas tempora asperiores incidunt qui quia. Id cumque iure vero dolores sit ipsa vel. Incidunt quis enim voluptas eos qui neque delectus. Totam dolore ratione voluptatem est labore et voluptatum. Repellat atque id hic doloribus vitae. Suscipit officiis architecto facere natus. Recusandae qui qui iste qui. Ducimus maiores nisi velit rem et. Odio provident doloribus repellendus molestiae harum laborum. Suscipit quasi aut soluta maxime repellat. Vel veritatis quo consequatur aspernatur qui atque in. Dolore saepe debitis eveniet qui architecto sit fuga.',
      contractType: 'CDI',
      duration: 2,
      remote: false,
      studyLevel: 'CAP',
      startDate: '2024-11-04',
    },
    company: {
      name: 'Capgemini',
      websiteUrl: 'https://www.baumbach.biz/quas-sunt-id-occaecati-aut',
      logo: 'total.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://waelchi.net/ipsam-et-voluptatibus-et-qui-ea.html',
    tag: ['Cybersécurité', 'Gestion de Projet', 'Ressources Humaines'],
    status: 'published',
    createdAt: '2024-10-14T19:10:55+02:00',
    endDate: '2024-11-14T00:00:00+01:00',
    slug: 'comptable-senior',
    category: [
      {
        name: 'Ressources Humaines',
      },
    ],
    premium: true,
    dayLast: 21,
  },
  {
    publicId: 'KIQ8F2',
    title: 'Responsable Marketing Digital',
    place: {
      fullAddress: '511 Stuart Heights\nHomenickland, WI 56563',
      city: 'Paris',
      zipCode: '13000',
      latitude: 27.013,
      longitude: 6.465724,
    },
    job: {
      description:
        'Quae quia enim aut quo natus. Adipisci voluptatem est officia aliquam voluptatem quo quia. Nostrum nihil voluptas beatae non tempora maiores. Quas et minus dicta hic praesentium quis ea. Qui quidem dolorem molestias ipsum. Quia vero magni sunt aspernatur hic. Possimus eius amet minus commodi libero qui incidunt. Quod consequatur reiciendis quam minus voluptatibus voluptas. Aspernatur velit porro rerum facilis. Non doloribus asperiores ab architecto in saepe omnis. Impedit et fugiat culpa. Nesciunt nobis non sunt aut explicabo sed. Pariatur ut aut animi aut id. Ut quos quae rerum sit. Eum quos officia voluptatem repudiandae rerum commodi est porro. Consectetur corrupti est unde reprehenderit aut. Rem tenetur rerum quas id. Eum non excepturi labore cumque maxime. Corrupti quidem sit voluptatibus et. Vel aut aperiam necessitatibus non consectetur. Quo vel quos voluptas ex soluta culpa aut. Officiis porro eum enim animi iusto facilis. Accusamus quo adipisci alias deleniti qui. Consequatur rerum vitae qui quo officia quo. Sed omnis ut nesciunt occaecati accusamus cupiditate ea. Repudiandae inventore esse atque eum eaque suscipit cupiditate. Doloribus impedit qui magni quos explicabo asperiores. Voluptatem corporis quia nostrum quas harum beatae hic. Non quo ut et quaerat. Ut hic incidunt iste quaerat aperiam vero enim. Eius et inventore autem omnis. Cumque illo molestiae quaerat autem dolore. Porro quia quia omnis vitae autem.',
      contractType: 'CDD',
      duration: 4,
      remote: true,
      studyLevel: 'Bac',
      startDate: '2024-10-29',
    },
    company: {
      name: 'Google',
      websiteUrl:
        'https://www.kshlerin.com/exercitationem-perferendis-consequatur-et-sapiente-est-et-consequatur-perspiciatis',
      logo: 'google.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://nitzsche.com/rerum-sit-non-et-quis-sit-aspernatur',
    tag: ['Apprentissage Automatique'],
    status: 'published',
    createdAt: '2024-10-14T19:07:54+02:00',
    endDate: '2024-11-14T00:00:00+01:00',
    slug: 'responsable-marketing-digital',
    category: [
      {
        name: 'Marketing Digital',
      },
    ],
    premium: true,
    dayLast: 21,
  },
  {
    publicId: 'KX6YG0',
    title: 'Analyste Financier',
    place: {
      fullAddress: '84934 Brandy Ville\nEmmerichbury, ND 04696',
      city: 'Lille',
      zipCode: '76600',
      latitude: -87.697279,
      longitude: 121.446757,
    },
    job: {
      description:
        'Est placeat dolores est illum autem. Quam saepe est tenetur temporibus quam distinctio. Numquam quis quos ut fugit. Non rem ullam quaerat non praesentium est quasi. Quia doloribus sed voluptate modi aliquam fugiat. Neque explicabo quibusdam nihil accusamus error. Perferendis ad earum et dolor eum. Velit unde omnis facilis et nisi quia minima. Nesciunt non nihil deleniti quasi cumque numquam iste qui. Consequatur nobis sapiente enim perspiciatis sed et provident placeat. In repellendus qui quasi deserunt quaerat. Quo magnam ab quia perferendis aliquid. Ipsa ipsam sunt consequatur sunt facilis. Vero perferendis porro doloribus qui ipsa. Ut officia aliquam ad et. Possimus corrupti molestiae quam ut accusantium fugiat aperiam. Iure eius voluptas et autem qui. Soluta non velit ipsam maiores et veniam. Maiores unde ipsam quia consequuntur nesciunt eum officia. Quisquam autem nisi voluptas. Nostrum dicta architecto accusantium deleniti repellat numquam qui. Iure recusandae et sed nam. Necessitatibus dolores explicabo in aut ut doloremque in. Aliquid amet enim pariatur animi cupiditate assumenda nostrum tenetur. Ad fuga consequatur deleniti molestiae itaque sit voluptatem ut. Mollitia impedit possimus distinctio est eveniet inventore minima numquam. Cumque et ut non omnis dolorum praesentium. Quisquam iusto ab dolores nihil. At repellat voluptas a sit debitis vitae. Vel aut quas sint.',
      contractType: 'Alternance',
      duration: 12,
      remote: false,
      studyLevel: 'CAP',
      startDate: '2024-11-05',
    },
    company: {
      name: 'Carrefour',
      websiteUrl:
        'http://www.rodriguez.org/id-perferendis-quidem-quia-et-cumque-ratione-laborum-in',
      logo: 'capgemini.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://www.raynor.info/cum-laboriosam-ipsa-at-rem',
    tag: ['Comptabilité', 'Développement Web'],
    status: 'published',
    createdAt: '2024-10-13T13:00:55+02:00',
    endDate: '2024-11-13T00:00:00+01:00',
    slug: 'analyste-financier',
    category: [
      {
        name: 'Informatique en Nuage',
      },
    ],
    premium: true,
    dayLast: 20,
  },
  {
    publicId: 'QT4I0B',
    title: 'Responsable Logistique',
    place: {
      fullAddress: '9582 Brown Drive Apt. 212\nLake Janie, ID 70884',
      city: 'Lyon',
      zipCode: '34000',
      latitude: -33.300239,
      longitude: 82.890192,
    },
    job: {
      description:
        'Excepturi unde dicta sed qui. Veniam iste voluptate dolores voluptatem cupiditate quia dolorem aut. Voluptates asperiores autem error tempore est suscipit. Aut ratione eligendi est sapiente. Atque nihil earum aliquid voluptatum exercitationem ut modi. Enim dolores necessitatibus non aut dolor quos aut. Deleniti a et neque fuga qui blanditiis. Reiciendis et libero qui est doloribus animi asperiores. Et sit neque nostrum dolor voluptatem ab harum fuga. Maiores excepturi minus voluptatibus sapiente. Quae quod sint eum nam repellat minima labore deleniti. Est et aut sit in dolores est ut. Laudantium rem officia nostrum laboriosam tempore. Ad et omnis nam quia dolorem voluptate dolor. Ratione nesciunt consequatur dignissimos voluptatem enim at suscipit. Unde ea vero ratione maxime fugiat non pariatur. Itaque itaque voluptates aut. Quam delectus quibusdam soluta doloribus in. Cupiditate earum esse nemo quae voluptas repellendus. Ipsam qui corrupti veniam voluptates. Mollitia consequuntur officia ut vel. Doloribus nemo consequatur deleniti odit dolore nisi tenetur. Quaerat voluptatem officia voluptate mollitia quibusdam aut incidunt. Ipsam ut occaecati commodi non. Quam ea ratione consequuntur aut. Voluptas maiores et fugit eum tempora quos dolorem. Dolore voluptatibus quia repellendus rerum. Unde sit quo rerum est numquam quisquam. Eaque ipsam fugit culpa ullam dolorem possimus ab.',
      contractType: 'Alternance',
      duration: 7,
      remote: true,
      studyLevel: 'CAP',
      startDate: '2024-11-09',
    },
    company: {
      name: 'Laboratoires Expanscience',
      websiteUrl: 'http://www.prohaska.com/et-id-cupiditate-ipsam-quasi-quod-delectus-dolores',
      logo: 'capgemini.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://www.weissnat.com/',
    tag: ['SEO/SEA'],
    status: 'published',
    createdAt: '2024-10-13T06:52:32+02:00',
    endDate: '2024-11-13T00:00:00+01:00',
    slug: 'responsable-logistique',
    category: [
      {
        name: 'Apprentissage Automatique',
      },
    ],
    premium: false,
    dayLast: 20,
  },
  {
    publicId: '51UAP6',
    title: 'Consultant en Ressources Humaines',
    place: {
      fullAddress: '2775 Arden Port Apt. 221\nPort Christa, KY 75823',
      city: 'Rennes',
      zipCode: '51100',
      latitude: -3.14975,
      longitude: 177.99374,
    },
    job: {
      description:
        'Aspernatur veritatis dicta reiciendis doloribus et ut vitae. Sequi velit sed consequatur consequuntur quasi corporis. Et voluptatem non assumenda in natus ex labore tempore. Totam deleniti quod officiis voluptatem a occaecati similique. Aliquid magni ut eaque impedit amet at. Est et quis temporibus ut. Sed id rerum reprehenderit dolores ipsum mollitia natus. Animi nostrum voluptatem possimus. Similique impedit fugit aut et. Beatae distinctio harum soluta soluta qui perspiciatis. Dolores odit animi maxime. Odio quaerat non eius deserunt. Animi tenetur quaerat suscipit eum rem et sint. Aliquid quia nulla qui sequi et fugit. Iste illum numquam ad quae quibusdam dolores. Est esse voluptatem et animi omnis repellat impedit est. Soluta molestiae quam est est. Voluptas non distinctio molestias quod totam. Accusantium quo mollitia ullam eligendi iure. Esse voluptas amet aliquam enim. Occaecati magni tempora explicabo perspiciatis nulla incidunt. Est laborum delectus temporibus tenetur quas alias sit. Maiores voluptas voluptatem eveniet id rerum aspernatur. Voluptatum voluptatem numquam sint consequatur aliquid et. Voluptates adipisci reiciendis et expedita et molestiae ad repellendus. Dolores minus ea quod occaecati tenetur iste dolorum. Occaecati quas ut est molestias enim temporibus. Unde vel nisi voluptatem aut repudiandae tempore eum. Et eius alias nemo enim. Nobis et assumenda aut reiciendis provident et eaque labore. Aliquam odit rerum impedit ex aperiam sit.',
      contractType: 'CDD',
      duration: 8,
      remote: true,
      studyLevel: 'Sans diplôme',
      startDate: '2024-11-03',
    },
    company: {
      name: 'Total',
      websiteUrl: 'https://www.bradtke.net/pariatur-qui-amet-velit-labore-voluptatem-architecto',
      logo: 'edf.png',
      verified: true,
      offerNumber: 1,
    },
    url: 'http://brown.biz/eum-omnis-consequatur-veritatis',
    tag: [
      'Comptabilité',
      'Science des Données',
      'Cloud Computing',
      'Support IT',
      'Marketing Digital',
    ],
    status: 'published',
    createdAt: '2024-10-13T01:19:06+02:00',
    endDate: '2024-11-13T00:00:00+01:00',
    slug: 'consultant-en-ressources-humaines',
    category: [
      {
        name: 'Cybersécurité',
      },
    ],
    premium: true,
    dayLast: 20,
  },
]
